# Use an official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend code
COPY backend /app/backend

# Install dependencies
RUN pip install fastapi uvicorn watchfiles python-dotenv matplotlib python-multipart langchain_openai

# Expose port for FastAPI
EXPOSE 8000

# Run the backend server
CMD ["uvicorn", "backend.app:app" , "--host", "0.0.0.0", "--port", "8000", "--reload"]
