# Use an official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the frontend code
COPY frontend /app/frontend

# Install dependencies
RUN pip install streamlit requests pillow

# Expose port for Streamlit
EXPOSE 8501

# Run the frontend server
CMD ["streamlit", "run", "frontend/frontend.py", "--server.address=0.0.0.0"]
